# Generated by Django 4.2.6 on 2023-11-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0003_reservations_loans'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
