# Generated by Django 4.2.6 on 2023-11-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0004_books_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='bookking_date',
            new_name='reserve_date',
        ),
    ]
