# Generated by Django 4.2.6 on 2023-11-29 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0005_rename_bookking_date_reservations_reserve_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='tracking',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
